import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import Author from "../../components/Author";
import EmailCapture from "../../components/EmailCapture";
import Footer from "../../components/Footer";
import Headline from "../../components/Headline";
import Title from "../../components/Title";
import styles from "../../styles/Article.module.css";

const Article: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Title />

        <Headline>
          4 things nobody tells you about preselling your product
        </Headline>

        <Author />

        <p>So, you’re thinking about pre-selling your product, eh?</p>
        <p>
          There’s a good chance you’ve experienced pre-selling one way or
          another. Maybe you backed a Kickstarter, or ordered a new book you
          were excited about. If you’ve ever bought tickets to a live event—a
          conference, workshop, or even a concert—you might consider that a kind
          of pre-selling as well!
        </p>
        <p>
          In all cases, you’ve paid in advance, and without any way to try
          before you buy.
        </p>
        <p>
          <em>But now you’re gearing up to be the seller.</em> On this side of
          the transaction, it feels a little different! This time it’s you
          asking people for their money before you’ve finished your product,
          with the promise that you’ll deliver it when it’s ready.
        </p>
        <h2>A great subheading</h2>
        <p>
          If you’ve already done the work to earn your audience’s trust and
          attention, and you’ve done the research to make a thing you’re pretty
          confident they’d want to buy, presales can be a great way to build
          momentum and excitement!
        </p>
        <h3>A sub-section</h3>
        <p>
          A few of the most popular upsides of pre-selling a product include:
        </p>
        <ul>
          <li>
            evidence that people want the thing you’re making, and the
            confidence you won’t launch something that nobody buys
          </li>
          <li>
            cash upfront that you can use to invest in producing the product
            itself, covering hard costs or simply buying more of your own time
            to work on delivering the product
          </li>
          <li>
            early feedback from your most motivated buyers that can help you
            improve your product before you stamp it as “done” and ready to ship
          </li>
          <li>
            social proof that you can use in your primary launch, from raw sales
            numbers to buyer testimonials, etc. your early buyers might even
            help spread the word about your product
          </li>
        </ul>
        <p>
          These are some pretty big upsides, honestly! No surprise that
          pre-selling is a popular choice.
        </p>
        <h3>Another sub-section, a little longer</h3>
        <p>
          But it’s far less common to hear about the downsides of pre-selling.
        </p>
        <h2>Another great subheading, this time a bit longer</h2>
        <p>
          Over in the 30x500 community chat, alumni Dave Ceddia (Pure React,
          Recut) opened up about some of his experiences with
          pre-sales…including the gnarlier parts.
        </p>
        <p>
          “There are a few downsides that I saw, pretty much all emotional. In
          my opinion they’re worth weighing for yourself because if I’m feeling
          awful, I have a very hard time getting myself to do the work.”
        </p>
      </main>

      <EmailCapture />

      <Footer />
    </div>
  );
};

export default Article;
