import type { NextPage } from "next";
import Head from "next/head";
import Headline from "../components/Headline";
import EmailCapture from "../components/EmailCapture";
import Title from "../components/Title";
import ArticleList from "../components/ArticleList";
import Footer from "../components/Footer";

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <Title />

      <Headline>The job-to-be-done</Headline>

      <EmailCapture />

      <ArticleList />
    </main>

    <Footer />
  </div>
);

export default Home;
